version: "3"

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vovan46rus/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: vovan46rus/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend

  gateway:
    image: vovan46rus/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static/
      - media:/media
    depends_on:
      - frontend
    ports:
      - 9000:80
